name: Daily Update Numbers

on:
  schedule:
    - cron: '30 19 * * *'  # UTC 19:30 (北京时间次日 03:30)
  workflow_dispatch:

jobs:
  update-numbers:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 检出 gh-pages 分支
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    
    # 2. 检出 main 分支的 Python 脚本到临时目录
    - name: Checkout main for script
      uses: actions/checkout@v2
      with:
        ref: main
        path: temp-main
    
    # 3. 设置 Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    # 4. 运行 Python 脚本（使用正确的路径）
    - name: Run Python script
      run: |
        # 复制脚本到当前目录
        cp temp-main/scripts/num.py .
        # 运行脚本
        python num.py
    
    # 5. 提交更改
    - name: Commit and push if changed
      run: |
        git config user.name 'GitHub Action'
        git config user.email 'action@github.com'
        git add files/
        git commit -m "Update numbers for $(date '+%Y-%m-%d')" || exit 0
        git push
